spring.application.name=api-gateway
server.port=8080


# Actuator
spring.cloud.gateway.metrics.enabled=true
management.endpoint.gateway.enabled=true

management.endpoints.web.exposure.include=health,info,metrics,gateway


