apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
      evaluation_interval: 10s

    scrape_configs:
      - job_name: 'production-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ["production-service:8081"]

      - job_name: 'delivery-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ["delivery-service:8082"]

      - job_name: 'inventory-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ["inventory-service:8083"]
