name: Deploy to K3s
on:
  workflow_run:
    workflows: 
      - "Java CI with Maven - production-service"
      - "Java CI with Maven - delivery-service"
      - "Java CI with Maven - inventory-service"
      - "Java CI with Maven - api-gateway"
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy manifests to K3s control plane
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.K3S_HOST }}
          username: ubuntu
          key: ${{ secrets.K3S_SSH_KEY }}
          source: "kubernetes-k3s/*.yaml"
          target: "~/"

      - name: Deploy to K3s
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.K3S_HOST }}
          username: ubuntu
          key: ${{ secrets.K3S_SSH_KEY }}
          script: |
            sudo k3s kubectl apply -f ~/kubernetes-k3s/
            sudo k3s kubectl rollout restart deployment
